### ISSUE TITLE
Design suggestions

### ISSUE THREAD

**Issue by bspeare** [uiowa/brand-icon-browser#1]
![iconbar-01](https://user-images.githubusercontent.com/1036433/168327262-436459c6-74dc-438e-a396-25604c515327.png)

Older screenshot:
<details>
![browser-01](https://user-images.githubusercontent.com/1036433/168318471-7a5f0320-d35f-4c99-b2eb-6e2af88597ca.png)
</details>

- ~Use a headline style from UIDS for "Brand Icon Browser"~
  -  ~Bring headline down so that it is visually grouped with search and tags.~ 
- Remove heading and use brand bar instead
- Search form
  - Utilize search form styles from uids_base as seen on "find your major" section on https://admissions.uiowa.edu/.  
- Reduce amount of "search examples" tags to one line.
  - Reduce font size by .1rem. 
  - Can we lose the `#` in the examples?
- Move One color, Two Color buttons into a button group within the gray results area.
  - Add an "All" option?
- Remove icons from all buttons - the icons are too complex to be used at such a small size.
  - Let the focus be on the icons displayed in the search results area.
- Move the filter list up and align it with the button group
  - Simplify active menu styles to just bold text.  The extra rectangle highlighting conflicts with all of the other boxes on the page.  
  - Increase font size, letter spacing, and line-height a bit.

**Comment by GaryRidgway** [comment]
- Consistent borders: different buttons have different border widths, could we standardize on one of: No border or 1px border?
- Is it possible to change the BG on white lined icons to a checkered Background? The first time I saw them, considering they were PNG only, I thought that it was a black square with a white lined icon over top.
- If we are highlighting the One-color/Two-color buttons when they are toggled on, should we also use that same functionality with the search examples? Making them darker when clicked?
-  Missing Icons/ broken icons (This may just be something to pass on to icon maintainers)
    - Dental Icon is missing in one color
    - Wifi icon is missing in one color
    - Wind turbine Icon is half missing in one color
    - Mouse icon has odd thinning at the bottom of it
    - Should we rename "Asian Arch" to "[Torii arch](https://en.wikipedia.org/wiki/Torii)"? I'm worrying about being to overly culturally general with the name.
- There is a thin strip of the community BG before the footer, can we remove that?
- I think people will understand what the search examples are, so i think we could probably remove the "Search examples:" label text

**Comment by GaryRidgway** [comment]
I've submitted the issues to that repo, thanks Dustin!

**Comment by quamsta** [comment]
@bspeare 
> Move One color, Two Color buttons into a button group within the gray results area.
Add an "All" option?

This has been partially addressed in the latest commit to main:
<img width="1460" alt="Screen Shot 2022-05-17 at 4 17 20 PM" src="https://user-images.githubusercontent.com/472923/168911613-7bdb8e7e-48d9-4da9-bac1-b2ca88399b9c.png">

There are a few issues with an "All" functionality:
- The intended use of the color switch feature right now is simply to flip between two base variants of the same set of icons  (one or two color). It's not meant to provide a way to compare the variants.
- Adding an additional "cloned" set of icons using an "All" feature would add an additional maximum of 502 items to the list of icons we're presenting, which may require paginating or a "loading as you scroll" sort of thing and that may just be overwhelming to the user. 
- The variants of the icons are not treated as separate icons, and it may be confusing to users that may think that each variant is a separate icon, when really it's more like a different color option for the same icon.

**Comment by quamsta** [comment]
Alternate search idea I'm mocking up:
<img width="1628" alt="Screen Shot 2022-05-17 at 4 35 13 PM" src="https://user-images.githubusercontent.com/472923/168914080-285e6c8e-75bf-4686-b0b5-4f4ad77b0262.png">

**Comment by quamsta** [comment]
I'm digging it too, and it helps solve a few design and usability issues brought up:

> Remove heading and use brand bar instead
This will be easier without the large "Brand Icon Browser" heading

> Reduce amount of "search examples" tags to one line.
> Reduce font size by .1rem.
> Can we lose the # in the examples?

Search examples are now in the placeholder for the input field.


I've put it in a new branch for now, but may merge it into main soon.

I've put a demo of the new search here:

https://sandbox.imu.uiowa.edu

**Comment by quamsta** [comment]
Closing these out for now, since a lot of these design suggestions are based on the older design from the spring.
