### ISSUE TITLE
Skeleton loading approach.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/brand-icon-browser#14]
First page load is jittery,[ should we be offering grey boxes on load like youtube, facebook, or storybook?](https://stackoverflow.com/questions/49962206/how-to-do-what-youtube-does-with-the-grey-boxes-while-loading)

**Comment by GaryRidgway** [comment]
This might be a useful resource
https://learnvue.co/2020/04/vue-skeleton-loading-screen-using-suspense-components-daily-vue-4/#how-is-our-skeleton-loading-screen-going-to-work

**Comment by quamsta** [comment]
Yes, possibly. haven't had time to dive into/looking at these, but here's my favorite skeleton GIF:

https://media1.giphy.com/media/5MxvgLxp5p732/200.gif
