### ISSUE TITLE
PNG only icons

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/brand-icon-browser#15]
are the bottom two icons (Yellow lined and white lined) supposed to be png only? I feel as though, If we have svgs, we should be able to color them similarly?

**Comment by quamsta** [comment]
We can... I think the idea is that if you're downloading the one color SVG, that you can use whichever tool of your choosing (Adobe Illustrator, text editor, Inkscape, the GIMP) to adjust the fill color on the vector image file. Right now with the `sharp`-based `imageLoad.js` process I'm using, I don't have a way to auto generate these variants.

**Comment by GaryRidgway** [comment]
Understandable, then this is not necessary!
