### ISSUE TITLE
Brand Icon Browser - Production deployment and server options

### ISSUE THREAD

**Issue by quamsta** [uiowa/brand-icon-browser#21]
The agreed upon domain between OSC and dev team is:

`icons.brand.uiowa.edu`

Opening the discussion here about where to host this application. Options that initially crossed my mind are:

- ~~On prem server~~
- GitHub Pages
  - Similar to [Admissions Viewbook GitHub actions](https://github.com/uiowa/admissions-viewbook/actions/workflows/gh-pages.yml)?
- ~~CloudFlare~~
- ~~Acquia (https://support-acquia.force.com/s/article/360006384074-Maintaining-a-static-microsite-alongside-Drupal-s-docroot)?~~

**Comment by bspeare** [comment]
I agree, GitHub sounds like a good place to start.

**Comment by quamsta** [comment]
Cool, I'll start putting together something similar to what I'm seeing on [Admissions Viewbook GitHub actions](https://github.com/uiowa/admissions-viewbook/actions/workflows/gh-pages.yml).

Thanks!

**Comment by quamsta** [comment]
This has been resolved with https://github.com/uiowa/brand-icon-browser/pull/51
