### ISSUE TITLE
Brand Icon Browser - Integrate Google Analytics and track events

### ISSUE THREAD

**Issue by quamsta** [uiowa/brand-icon-browser#26]
To do:

- [x] Set up GA property
- [x] Integrate GA via `vue-gtag` or something similar

Ideas for sorts of things we can learn/do with analytics:

- Which icons are downloaded most
- What people are searching for
  - Potential gaps in tagging 
  - Additional/new icons that may be needed
- Which categories are most popular
- Could populate a "trending" or "commonly searched for" section in the Icon Browser itself

**Comment by quamsta** [comment]
Looking into using[ vue-gtag](https://matteo-gabriele.gitbook.io/vue-gtag/) for this, unless anyone else has any ideas about easily integrating GA into vuejs?

**Comment by mjoneill** [comment]
Partners want visibility into search queries to so that a Sondra can get a sense of what types of icons don't exist but people are looking for. 

Also what icons are being downloaded, which ones are more popular than others, ok.
