### ISSUE TITLE
Allow aspect ratio options for download

### ISSUE THREAD

**Issue by bspeare** [uiowa/brand-icon-browser#3]
# Problem

All of the icons have no padding around them and when they are uploaded to a website they look pretty bad. 

# Proposed solution

I just noticed this on the nounproject.com (see screenshot below).   When I use icons on SiteNow I always have to resize them in Photoshop to get enough space around the icon.   I wonder if we could implement some sort of aspect ratio option when downloading?

<img width="1009" alt="Screen Shot 2022-05-20 at 12 37 04 PM" src="https://user-images.githubusercontent.com/1036433/169582714-c7220a78-fedf-4108-8c2a-55429a351c30.png">

**Comment by quamsta** [comment]
@bspeare 

I'm going to be working on a branch that will use [the Sharp NodeJS library](https://sharp.pixelplumbing.com/) to do this automatically. We also may be able to generate the png variations with this library.

Ideally I'd like to take this further and the `brand-icons` branch can just contain two SVGs per icon, the one and two color variations and we can use Sharp to generate the other formats and variants.

**Comment by quamsta** [comment]
Closing this, since it's been implemented
