### ISSUE TITLE
Alternate sidebar category list icon ideas

### ISSUE THREAD

**Issue by quamsta** [uiowa/brand-icon-browser#4]
Here are some alternate ideas for the category / sidebar icons, may update as I come across more:

# Icon ideas

## All Brand Icons
 - open-book (current)

## Recently added
 - calendar-clock (current)
 - clock
 - hourglass

## Academics and Research
- graduation-cap (current)
- calculator
- hand-writing-with-pen

## Campus Buildings
- imu (current)
- old-capitol
- residence-hall
- cityscape-tree

## Entertainment and Dining
- popcorn (current)
- party
- disco-ball
- drama-masks
- cookies

## Home and Personal
- house (current)
- friendship
- heart_1
- person-one
- donate

## Nature and Recreation
- tree-one (current)
- leaf
- daisy
- poinsettia
- mountains
- tree-two
- basketball

## Patient Care
- doctor (current)
- doctor-case
- cross-medical
- heartbeat (may not work if we use heart_1 for personal)

## Technology and Business
- cellphone (current)
- computer-monitor
- cursor
- printer
- briefcase

## Wayfinding and Transportation
- map-pin (current)
- warning
- arrow-direction
- pointer-finger
- directional-sign

**Comment by bspeare** [comment]
How about we stick with the current icons, except switch out `imu` with `residence-hall` and set the height to 30px?

.category-list-item__icon {
    height: 30px;
}

**Comment by quamsta** [comment]
Yeah, that works! Do any of the alternate icons stick out to you besides imu -> residence-halls ?

**Comment by bspeare** [comment]
These might look better at that smaller size:

- entertainment > `drama`
- home >  `person-one` 
- patient > `doctor-case`
- technology > `cursor`
- wayfinding > `arrow`

**Comment by quamsta** [comment]
Here are some alternate ideas based on those suggestions, only change is `doctor-case` was a bit too small at that size so i used `cross-medical` instead, and changed out Recently added to just be a clock, since `calendar-clock` was also a bit too small:

<img width="277" alt="Screen Shot 2022-05-23 at 10 05 39 AM" src="https://user-images.githubusercontent.com/472923/169849596-383aee20-d3ff-47df-8d9c-11662836b63c.png">

**Comment by bspeare** [comment]
Those look good!
