### ISSUE TITLE
Use cards for icon list

### ISSUE THREAD

**Issue by pyrello** [uiowa/brand-icon-browser#6]
# Motivation

The icon list is essentially already using a card-like structure for icons. I think we should adopt the card component for this to enhance consistency with our existing look/feel.

**Comment by quamsta** [comment]
I'm hesitant about making the actual `icon-list__button` into a card. After reviewing [the existing card component](https://uids.brand.uiowa.edu/components/detail/card--default.html) on uids.brand.uiowa.edu, it's clear that the `card` component is meant to be used for linking to typical full website content (especially with its image, a headline,  byline, text description, button). 

I worry that trying to fit an application-specific component with a very different use case like the `icon-list__button` into a card structure is sort of testing the limits of what a `card` is.

I feel there's utility in keeping components that have vastly different purposes separate from each other to prevent the need for a bunch of different bem modifiers to accommodate the new purpose and allows for easier adjustments to one without affecting the other.

**Comment by quamsta** [comment]
> The card component was designed to be very versatile and is the most basic representation of a "thing" on a website. It doesn't need to link to anything. Most of the fields can be omitted.

This is the thing that bothers me the most. I don't believe components should be able to represent something as vague as a "thing" on the web or in any user interface. In my opinion, components should have a specific purpose or use-case and should not serve as a catch-all for "something that is in a box."

Components should have variations in terms appearance and a bit of general flexibility of course, but their purpose and where they're used should be specifically outlined to prevent overuse and having them balloon in complexity.

**Comment by pyrello** [comment]
It sounds like maybe you have some opinions about what components we need to have in UIDS 🙂 We are in the process of defining the 4.x version of basically everything, so hearing other opinions could be helpful in getting us to the best outcome. Here is an issue I opened related to the card component: https://github.com/uiowa/uids/issues/696. If you want to make the case for why you think we need more components than just the card and share your ideas about how that should work, I'd be happy to hear them!

With regard to this, I guess I'm not sure what your objection here is, except that you seem to not like generalized components on principle. Otherwise, there is a pretty clear match between the icon list button and the card. The card can consist of an image, a title, and be linked. Our solution even accounts for using the label/title as the aria-label while not creating duplicate or nested links to be more a11y-friendly.

If you genuinely believe that your component is something other than a card, then what is it? We are trying to make UIDS more compatible with applications, so if this is clearly a different paradigm than a button, then we probably should figure out how to get it in there.

**Comment by quamsta** [comment]
I'm slowly coming around to the idea of a more vague card component after doing some research on some other design systems and their cards and their intended purposes like [Google's material cards and their flexibility](https://m3.material.io/components/cards/specs), but for the time being, I'd like to keep the icon list buttons as an app-specific component. 

I feel the softer, more subtle borders with a small amount of radius matches the softer-edged style of the icons themselves, and there's a nice hover effect that invites clicking on them, that may not be feasible in a standard card in its current form.

I like being able to reuse those softer gray borders in the `IconModal` component to provide consistency within the app. If the UIDS cards were designed with less harsh borders, edges, and other things, we might be able to make this work.

**Comment by quamsta** [comment]
A couple of additional reasons this component may not fit into a typical, as-is `card` component:

- A large number of these components need to be placed in a grid, which may require specific, less intrusive border thickness and color options in order to prevent the borders to become overwhelming when scrolling through a large set of them. 
- Adding a style to `card` that would accommodate the above concern may be misconstrued or misused on a `card` component where there aren't dozens of them on screen at the same time.

**Comment by quamsta** [comment]
Closing this out for now.
